apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.20.1
    helm:
      values: "nameOverride: argo\nexecutor:\n  resources:\n    requests:\n      cpu: 200m\n      memory: 256Mi\n    limits:\n      cpu: 1\n      memory: 1024Mi\nserver:\n  extraArgs:\n  - --secure\n  - --auth-mode=client\n  - --auth-mode=sso\n  ingress:\n    enabled: true\n    ingressClassName: nginx\n    annotations:\n      cert-manager.io/cluster-issuer: \"letsencrypt-prod\"\n    hosts:\n      - argo.<DOMAIN_NAME>\n    paths: \n      - /\n    pathType: Prefix\n    tls:\n        hosts:\n          - argo.<DOMAIN_NAME>\n  sso:\n    issuer: https://vault.<DOMAIN_NAME>/v1/identity/oidc/provider/kubefirst\n    clientId:\n      name: argo-secrets\n      key: client-id\n    clientSecret:\n      name: argo-secrets\n      key: client-secret\n    redirectUrl: https://argo.<DOMAIN_NAME>/oauth2/callback\n    scopes:\n      - email\n      - openid\n      - groups\n      - user\n      - profile\n    # RBAC Config. >= v2.12\n    rbac:\n      enabled: true\nuseDefaultArtifactRepo: true\nuseStaticCredentials: true\nartifactRepository:\n  archiveLogs: false\n  s3:\n    accessKeySecret:\n      name: ci-secrets\n      key: accesskey\n    secretKeySecret:\n      name: ci-secrets\n      key: secretkey\n    insecure: false\n    bucket: <KUBEFIRST_STATE_STORE_BUCKET>\n    endpoint: <KUBEFIRST_STATE_STORE_BUCKET_HOSTNAME>\n    region: us-east-1\n    useSDKCreds: false\n    encryptionOptions:\n      enableEncryption: false"
    chart: argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
