metaphor:
  image:
    repository: <CONTAINER_REGISTRY_URL>/metaphor
  ingress:
    className: nginx
    enabled: true
    annotations:
    hosts:
    - host: metaphor-development.<DOMAIN_NAME>
      paths:
      - path: /
        pathType: Prefix
    tls:
      hosts:
      - metaphor-development.<DOMAIN_NAME>
  metaphor:
    host: https://metaphor-development.<DOMAIN_NAME>/api
    console: https://kubefirst.<DOMAIN_NAME>
