apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <ENVIRONMENT>-environment-metaphor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '45'
spec:
  project: default
  source:
    repoURL: <GITOPS_REPO_URL>
    path: registry/environments/<ENVIRONMENT>/metaphor
    targetRevision: HEAD
  destination:
    name: <WORKLOAD_CLUSTER_NAME>
    namespace: <ENVIRONMENT>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
