metaphor:
  image:
    repository: registry.gitlab.com/<GITLAB_OWNER>/metaphor
  imagePullSecrets:
  - name: docker-config
  ingress:
    className: nginx
    enabled: true
    annotations:
    hosts:
    - host: metaphor-staging.<DOMAIN_NAME>
      paths:
      - path: /
        pathType: Prefix
    tls:
      hosts:
      - metaphor-staging.<DOMAIN_NAME>
  metaphor:
    host: https://metaphor-staging.<DOMAIN_NAME>/api
    console: https://kubefirst.<DOMAIN_NAME>
  vaultSecretPath: staging/metaphor
