apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: <ALERTS_EMAIL>
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
    - dns01:
        webhook:
          solverName: 'civo'
          groupName: civo.webhook.okteto.com
          config:
            secretName: civo-secret
        selector:
          dnsNames:
          - '*.<DOMAIN_NAME>'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <ALERTS_EMAIL>
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
    - dns01:
        webhook:
          solverName: 'civo'
          groupName: civo.webhook.okteto.com
          config:
            secretName: civo-secret
        selector:
          dnsNames:
          - '*.<DOMAIN_NAME>'
