metaphor:
  image:
    repository: ghcr.io/<GITHUB_OWNER>/metaphor
  imagePullSecrets:
  - name: docker-config
  ingress:
    className: nginx
    enabled: true
    annotations:
    hosts:
    - host: metaphor-production.<DOMAIN_NAME>
      paths:
      - path: /
        pathType: Prefix
    tls:
      hosts:
      - metaphor-production.<DOMAIN_NAME>
  metaphor:
    host: https://metaphor-production.<DOMAIN_NAME>/api
    console: https://kubefirst.<DOMAIN_NAME>
  vaultSecretPath: production/metaphor
