apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: nginx-apex-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '11'
spec:
  project: default
  source:
    repoURL: https://github.com/digitalocean-https/gitops.git
    path: registry/test-digitalocean-api-9/components/nginx-apex
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
