apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: default
  source:
    repoURL: https://github.com/digitalocean-https/gitops.git
    path: registry/test-digitalocean-api-9/components/vault
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
