apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  replicas: 2
  template:
    spec:
      organization: digitalocean-https
      image: summerwind/actions-runner-dind
      serviceAccountName: github-runner
      dockerdWithinRunnerContainer: true
      automountServiceAccountToken: true
